[package]
name = "rosette_core"
version.workspace = true
edition = "2024"
description = "rosette核心"
authors.workspace = true

[dependencies]
# 错误处理
anyhow.workspace = true
# ros2包解析
rosbag2-rs.workspace = true
# ros1包解析
rosbag.workspace = true
# 临时文件
tempfile.workspace = true
# mqtt协议栈
rumqttc.workspace = true
rumqttd.workspace = true
# dds分布式通信
rustdds.workspace = true
# 静态变量
static_cell.workspace = true
# 全局变量
once_cell.workspace = true
# 通用数据表达序列化/反序列化
cdr.workspace = true
# 大小端字节序
byteorder.workspace = true
# ros2通信
ros2-client = { workspace = true, features = ["pre-iron-gid"] }
ros2-interfaces-humble.workspace = true
# 异步流处理
futures.workspace = true
# 日志前端
log4rs.workspace = true
# 日志后端
log.workspace = true
# 异步框架
tokio.workspace = true
