[package]
name = "rosette_cli"
version.workspace = true
edition = "2024"
description = "rosette命令行工具"
authors = ["qsbye <2557877116@qq.com"]

[dependencies]
# 命令行解析
clap.workspace = true
# 错误处理
anyhow.workspace = true
# 复杂命令解析
shell-words.workspace = true
# 宏编程, 减少重复代码
paste.workspace = true
# 多线程框架
tokio.workspace = true
